package com.restaurant.backend.entity;

public enum AuditAction {

    LOGIN,

    CREATE_ORDER,
    CHANGE_ORDER_STATUS,

    ASSIGN_WAITER,
    REASSIGN_WAITER,

    GENERATE_BILL,
    PRINT_BILL,
    MARK_BILL_PAID,

    CREATE_TABLE,
    CHANGE_TABLE_STATUS,
    DISABLE_TABLE,
    REGENERATE_QR,

    CREATE_RESERVATION,
    CONFIRM_RESERVATION,
    CANCEL_RESERVATION,
    SEAT_RESERVATION,
    COMPLETE_RESERVATION,

    CREATE_REVIEW,
    APPROVE_REVIEW,
    REJECT_REVIEW,
    HIDE_REVIEW,

    UPDATE_SETTINGS
}